### ISSUE TITLE
Does this use Style-Aligned?

### ISSUE THREAD

**Issue by olliacc** [GongyeLiu/StyleCrafter#1]
does this use https://github.com/google/style-aligned?

**Comment by GongyeLiu** [comment]
Thank you for your question. To clarify, we did not adopt [style-aligned](https://github.com/google/style-aligned). Our work was actually developed in parallel with it. Our approach mainly involves training a style adapter to generate images/videos in a specified style. You can refer to our [paper](https://arxiv.org/abs/2312.00330) for more detailed technical information.
