### ISSUE TITLE
self.to_k_style and self.to_v_style

### ISSUE THREAD

**Issue by dmmSJTU** [GongyeLiu/StyleCrafter#10]
https://github.com/GongyeLiu/StyleCrafter/blob/8d7ce622964ae63667ecb5fbd0013744e3558ce4/lvdm/modules/attention.py#L628
Hello, did self.to_k_style and self.to_v_style  need to be trained with Query-transformer? Or do you directly use to_k and to_v in latent-diffusion?

**Comment by GongyeLiu** [comment]
1. Yes, both are trained during the Stage 1. Please refer to our technique report for details.
2. The `to_k_style` and `to_v_style` refer to the style branch of the cross-attention layer, whereas `to_k` and `to_v` represent the original text branch of the cross-attention, they are different components.

**Comment by dmmSJTU** [comment]
Hello,  are to_k_style and to_v_style trained from scratch? Or they fine-tuned based on to_k and to_v?

从 Windows 版邮件发送

发件人: Liu Gongye
发送时间: 2024年8月24日 11:44
收件人: GongyeLiu/StyleCrafter
抄送: dmmSJTU; Author
主题: Re: [GongyeLiu/StyleCrafter] self.to_k_style and self.to_v_style(Issue #10)

1. Yes, both are trained during the Stage 1. Please refer to our technique report for details.
2. The to_k_style and to_v_style refer to the style branch of the cross-attention layer, whereas to_k and to_v represent the original text branch of the cross-attention, they are different components.

**Comment by GongyeLiu** [comment]
No, they are initialized from the `to_k` and `to_v`'s parameters. Then `to_k` and `to_v` are fixed, `to_k_style` and `to_v_style` are finetuned(along with other parameters).

**Comment by dmmSJTU** [comment]
Got it. Thank you very much.
In the paper, “for target image, we scale the shorter side of the image to 512 and then crop the target content 
from the central area;”  假如原始图像H=300 w=1024，根据文中的说法就是w不变，H resize为512。是这样理解吗？

从 Windows 版邮件发送

发件人: Liu Gongye
发送时间: 2024年8月24日 23:43
收件人: GongyeLiu/StyleCrafter
抄送: dmmSJTU; Author
主题: Re: [GongyeLiu/StyleCrafter] self.to_k_style and self.to_v_style(Issue #10)

No, they are initialized from the to_k and to_v's parameters. Then to_k and to_v are fixed, to_k_style and to_v_style are finetuned(along with other parameters).

**Comment by GongyeLiu** [comment]
No, the aspect ratio will be maintained. 
Maybe this [repo](https://github.com/GongyeLiu/StyleCrafter-SDXL) can help you? We just released the training code of StyleCrafter-SDXL, detailed training settings are available in the code.

**Comment by dmmSJTU** [comment]
I got it. That’s great work. Thank you.

从 Windows 版邮件发送

发件人: Liu Gongye
发送时间: 2024年8月25日 1:19
收件人: GongyeLiu/StyleCrafter
抄送: dmmSJTU; Author
主题: Re: [GongyeLiu/StyleCrafter] self.to_k_style and self.to_v_style(Issue #10)

No, the aspect ratio will be maintained.
Maybe this repo can help you? We just released the training code of StyleCrafter-SDXL, detailed training settings are available in the code.
