### ISSUE TITLE
关于cfg 约束疑问

### ISSUE THREAD

**Issue by Vincento-Wang** [GongyeLiu/StyleCrafter#13]
![image](https://github.com/user-attachments/assets/84f63114-5889-4d90-9fb1-4b7756220dcb)

![image](https://github.com/user-attachments/assets/b7290aaf-3d90-437a-afdb-2772fd2403c7)

论文和代码 有些对不上，论文好像也没描述，因为修改了原版 CFG约束，random drop  策略是否也有修改呢

**Comment by GongyeLiu** [comment]
1. 关于论文和代码对不上的问题

我认为还是一致的。代码这里的三个变量：`e_t`: text cond + style cond; `e_t_uncond_style`: text cond only; `e_t_uncond`: no cond，和公式里应该是对应的。也可能我没太get到你的意思，或许可以再详细补充下。

2. random drop的策略

style cond是不需要进行random drop的，这是额外的分支，只要去掉这个分支就是unconditional generation了（当然做random drop也可以，类似ip-adapter）。对于text condition，我觉得要取决于基模型的random drop策略？这个repo下的模型是基于VideoCrafter1.0的，所以没有对text condition进行random drop。

同学你也可以参考下另一个基于SDXL的[repo](https://github.com/GongyeLiu/StyleCrafter-SDXL)，提供了训练代码。

**Comment by Vincento-Wang** [comment]
> 1. 关于论文和代码对不上的问题
> 
> 我认为还是一致的。代码这里的三个变量：`e_t`: text cond + style cond; `e_t_uncond_style`: text cond only; `e_t_uncond`: no cond，和公式里应该是对应的。也可能我没太get到你的意思，或许可以再详细补充下。
> 
> 2. random drop的策略
> 
> style cond是不需要进行random drop的，这是额外的分支，只要去掉这个分支就是unconditional generation了（当然做random drop也可以，类似ip-adapter）。对于text condition，我觉得要取决于基模型的random drop策略？这个repo下的模型是基于VideoCrafter1.0的，所以没有对text condition进行random drop。
> 
> 同学你也可以参考下另一个基于SDXL的[repo](https://github.com/GongyeLiu/StyleCrafter-SDXL)，提供了训练代码。

![image](https://github.com/user-attachments/assets/e3ba4bc0-4882-42df-b92d-42f2a9c723b7)
蓝色箭头这里，左侧应该是全条件的吧，代码是这样的，公式是无条件的

**Comment by GongyeLiu** [comment]
抱歉是的，这里确实有些不一致，感谢你的提醒！
不过影响应该没有特别大，推导如下：

![85071733504202_ pic](https://github.com/user-attachments/assets/35a09c3d-9101-4fda-a3f3-745cdf7f1805)

似乎就是系数差了一个常量，对超参以外的结论应该没有影响
