### ISSUE TITLE
请教一个问题啊

### ISSUE THREAD

**Issue by Vincento-Wang** [GongyeLiu/StyleCrafter#14]
如果基于DynamicCrafter做 image to video stylization ，有什么可行得思路吗，我实验中发现，风格图 和图生视频得参考图，都是同一张图，然后训练恢复原视频，收敛了，但是推理得时候换风格图，输出没有什么变化，因该是参考图条件过强，让风格没有学进去，
你训练时候分两个阶段得，一阶段是训练 文生图(帧数=1)还是 文生视频（帧数=16）啊，一阶段训完，如果不进行二阶段得微调，直接出来得视频，风格化有效吗，

**Comment by GongyeLiu** [comment]
你好同学，第一阶段训练的是文生图。如果不做微调的话，风格化还是有效的，但时序比较差。

我理解你说的I2V stylization是不带风格的参考图+风格图，生成带风格的视频？感觉应用上比较简单的方案是先做image style transfer，再做I2V animation？如果直接训练的话，没有配对数据感觉是很难学出来解耦的。

**Comment by Vincento-Wang** [comment]
> 你好同学，第一阶段训练的是文生图。如果不做微调的话，风格化还是有效的，但时序比较差。
> 
> 我理解你说的I2V stylization是不带风格的参考图+风格图，生成带风格的视频？感觉应用上比较简单的方案是先做image style transfer，再做I2V animation？如果直接训练的话，没有配对数据感觉是很难学出来解耦的。

有道理
