### ISSUE TITLE
Caption Preprocessing with regular expressions

### ISSUE THREAD

**Issue by EadCat** [GongyeLiu/StyleCrafter#7]
Dear author,
<img width="311" alt="20240508195612" src="https://github.com/GongyeLiu/StyleCrafter/assets/59416168/d4943d32-f09b-4d9e-abc2-3c4a05b98343">

I would like to know in detail about the BLIP2 caption preprocessing method used in the paper.

1. Which BLIP2 checkpoint was used? Was there no difference in performance between the checkpoints?
2. What regular expressions were used?
3. Whether the captions were processed by BLIP-2 itself or Python source code?

Your paper inspires me. Thank you, in advance.

**Comment by GongyeLiu** [comment]
Hi,
1. We use [blip2-opt-6.7b-coco](https://huggingface.co/Salesforce/blip2-opt-6.7b-coco) to generate captions. We haven't performed any ablations among different BLIP2 checkpoints. Personally I think there might be a minor difference but won't be significant.
2.  The code of regular expressions is partly listed as follows:
```python
import re

patterns = [
    r'^((a )?(\w+\s+)*(?:painting|drawing|mural|artwork|view|portrait|photo|photograph|watercolor|illustration|picture|digital art) of )+',
    r'in (a )?(\w+\s+)*(?:painting|drawing|mural|artwork|view|portrait|photo|photograph|watercolor|illustration|picture|digital art)\s?',
    r'^(?:painting|photograph|digital art|black and white photograph) - ',
]

for pattern in patterns:
    caption = re.sub(pattern, "", caption)
```
3.  I'm not quite figure out your question. We first use BLIP-2 to regererate captions for our image datasets(offline mode). Then we conduct regular expressions in dataloader as a preprocessing filter.

I hope these resolve your issue. If any further questions or concerns, please feel free to ask.

**Comment by EadCat** [comment]
The questions resolved clearly. Thank you!
